name: GymTracker
options:
  bundleIdPrefix: com.gymtracker
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true

targets:
  GymTracker:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Sources
        excludes:
          - "**/.DS_Store"
          - "**/*.py"
          - "**/Info.plist"
    info:
      path: Info.plist
      properties:
        CFBundleName: GymTracker
        CFBundleDisplayName: GymTracker
        CFBundleIdentifier: com.gymtracker.app
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
        LSRequiresIPhoneOS: true
        MinimumOSVersion: "16.0"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.gymtracker.app
      SWIFT_VERSION: "5.9"
      TARGETED_DEVICE_FAMILY: "1"
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Manual
      GENERATE_INFOPLIST_FILE: NO
      INFOPLIST_FILE: Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: "16.0"
